### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fwcd** [Holzhaus/triseratops#18]
Hi, the library looks really cool and I would love to use it in a GPL-licensed project (a music library management system).

Any reason for using AGPL over regular GPL here (the latter, I would imagine, might also make it easier to integrate it into Mixxx, which is GPL as well)?

(Just curious, you are of course free to license any way you like)

**Comment by Holzhaus** [comment]
> Any reason for using AGPL over regular GPL here (the latter, I would imagine, might also make it easier to integrate it into Mixxx, which is GPL as well)?

The reason is that I wanted to avoid that web services use my work for profit without even giving credit (I've experienced this before). Also, this library was primarily written for usage with [`aoide-rs`](https://gitlab.com/uklotzde/aoide-rs), which is also AGPL-licensed).

But I'm willing to consider licensing it under MPL-2.0 which would make it possible to use in your GPL-licensed project (I'm curious, do you have a link?). @uklotzde What do you think?

**Comment by fwcd** [comment]
Sure, this is the project: https://github.com/fwcd/bassment

Didn't know about aoide, interesting, looks like a similar idea!

**Comment by Holzhaus** [comment]
> Sure, this is the project: https://github.com/fwcd/bassment
>
> Didn't know about aoide, interesting, looks like a similar idea!

Yeah, although there are currently are no plans for an aoide frontend AFAIK, just the server part. We are planning to replace the library implementation of Mixxx with it in the long term.

> But I'm willing to consider licensing it under MPL-2.0 which would make it possible to use in your GPL-licensed project. @uklotzde What do you think?

Ping @uklotzde

**Comment by uklotzde** [comment]
@Holzhaus Sure, go ahead.

**Comment by uklotzde** [comment]
@fwcd I had a look at your project, interesting. You took a different approach with the fully normalized database schema and hierarchical structures stored in the database. My vision is to store the hierarchical presentation separately as a client-side configuration. Files are much more suitable for storing hierarchical structures than relational databases.

Don't look too closely at the aoide crates, they need to be consolidated at some point. Due to the lack of a proper frontend/UI development has stalled somehow. Unfortunately, I am not a frontend developer to actively move this forward.

I use the aoide web server for attaching my collection to Mixxx. It allows me to integrate a hierachical folder/group view of smart crates/playlists into Mixxx. Moreover the *media tracker* is much more advanced than what is found in Mixxx such that I can view recently modified files in a smart playlist and then manually reimport the tracks in Mixxx from time to time.

We also maintain a private repository for testing purposes which directly uses the `aoide-backend-embedded`, i.e. no web server or JSON serialization. This private repo contains some ugly Rust UI prototypes for managing collections on local directories. The directory contents are then recursively (and incrementally) ingested into both the SQLite database and a Tantivy fult-text search index. The entry points for those batch tasks can be found in `aoide-backend-embedded::batch`.

**Comment by fwcd** [comment]
> licensing it under MPL-2.0

Any update on this?

**Comment by Holzhaus** [comment]
Embarassing, I completely forgot about this.

**Comment by Holzhaus** [comment]
https://github.com/Holzhaus/triseratops/commit/98c4d7c312144fceeccb1751b1130764bb9f6b26
